### ISSUE TITLE
How to disable the --do qsm function 

### ISSUE THREAD

**Issue by huiyyu** [QSMxT/QSMxT#124]
I would like to run QSMxT 6.4.4 on some premade QSM images to do the segmentation and analysis. 

When I tried to use the command "qsmxt bids/ qsm/ --do_segmentation --do_analysis --auto_yes", the system output reminded me: 

> [WARNING]: --do_segmentation requires --do_qsm. Enabling --do_qsm.

Is it possible to disable the -do_qsm function?

**Comment by astewartau** [comment]
Hi @huiyyu, thanks for reaching out and thanks for your patience! Unfortunately I've been unavailable for the past few weeks to attend to QSMxT issues. However, if you try running the latest version v7.1.0, you will find that you are able to now run the steps without `--do_qsm`, and you should be able to generate segmentations, analysis results, and QSM results independently! 

The new usage also does not require an output directory, as the results are integrated straight back into the BIDS directory in a compliant manner. I am planning to add the output directory back as an optional flag in v7.2.0. 

Let me know if that works for you!

**Comment by huiyyu** [comment]
Hi @astewartau,

I appreciate your reply to my question! I had 3 further questions regarding the data preparation for this pipeline in this case.

a) The magnitude, T1, and QSM images are necessary to use the segmentation function of the pipeline, right? If so, can I only convert the magnitude, T1, and QSM nifti files into the BIDS format as the input data of the pipeline? 
b) Which command can I use to convert the qsm nifti file (e.g. sub-1_Chimap.nii.gz) into its BIDS format as you suggest?
c) Do I still need to fill the MagneticFieldStrength and EchoTime fields in the csv file to run the segmentation function after using the nifti-convert command?

**Comment by astewartau** [comment]
a) Actually, it should be that only the magnitude and T1 are necessary for segmentation. The T1 is segmented and then registered to the same space as QSM using the magnitude image. The QSM is then only necessary if you also want to export analysis CSVs via `--do_analysis`. I believe you should only need to convert the images needed into the BIDS format to run each step. 

b) The best way to convert NIfTI data to BIDS will be using `nifti-convert`. If you place all your NIfTI images into a directory, you can run `nifti-convert my-nifti-dir bids` to do the conversion. The conversion is only semi-automated, so it will generate a CSV for you to complete with various BIDS tags. Once it's filled out, you can run the same `nifti-convert` command to complete the conversion. As a quick example: 

![image](https://github.com/user-attachments/assets/6b85e3e9-202a-4dbd-95f3-5db817ce2fae)

c) You should not need values in those fields for QSM, but the `nifti-convert` tool might not allow you to do the conversion without at least some dummy values there.

**Comment by huiyyu** [comment]
I would like to use the `--do_analysis` function after segmentation, and thus the qsm nifti files should be necessary for me. I tried to use the `nifti-convert` tool to convert the t1, magnitude and qsm images into BIDS format. Although the tool generated the csv file like the example you provided, but the nifti files were not placed into the bids folder. The log file did not show any error message for this process. How can I fix this issue?

**Comment by astewartau** [comment]
The NIfTI files will not be placed into the BIDS folder until after you manually fill out the .CSV file, save it, and then run the command again. If following these steps still doesn't work, could you please paste the full output of the command?

**Comment by huiyyu** [comment]
Running the command again did move the qsm, magnitude and t1 nifti files into the bids/sub-*/anat folder. So the issue seems to be solved.

There are a warning and an error messages when using the `--do_qsm` and `--do_analysis` tools after that.

> [WARNING]: No files found matching pattern: /path/to/pipeline/bids/sub-*/anat/sub-*_part-phase*.nii*
> [ERROR]: Workflow is empty! There is nothing to do.
> [INFO]: Warnings occurred!
> [INFO]: Errors occurred!

How can I solve this problem?

**Comment by astewartau** [comment]
Hi @huiyyu, and thanks for your patience! 

1. That's right - if you have any `_Chimap` or `_dseg` files available in your derivatives folder, they will be included in the `--do_analysis` step automatically. 
2. Yes, the DerivativePipeline value is required and will result in dicom-convert automatically placing the file in `bids/<DerivativePipeline>/sub-[x]/...` etc. as needed. There is currently no way to automatically fill this value of the spreadsheet - you will need to do this manually in Excel or LibreOffice or another CSV editor. 

About the error messages - can you paste the full output of `tree /path/to/pipeline/bids` so I can confirm that the structure of your BIDS directory is correct? Could I also see the details in the CSV?

About segmentation:

a) Yes, co-registration is performed using ANTs and registers the T1-weighted image to the magnitude image in the QSM space. 
b) The pipeline uses FastSurfer for the segmentation step, which uses the T1-weighted image without any corrections. FastSurfer does not explicitly require corrections, but if you find that they improve the quality, I can definitely add a bias correction step or other corrections if you can follow-up about this with references or results. Otherwise, it could be something I test at a later date. 
c) To evaluate segmentation performance, I can only refer you to the FastSurfer paper and their own analyses about segmentation performance - or you could compare it with other techniques like manual segmentation. Unfortunately it does not include a confidence measure or other metrics to self-evaluate.

**Comment by weblearn22** [comment]
Hi @astewartau,

The output of `tree /path/to/pipeline/bids`: 
![image](https://github.com/user-attachments/assets/9a31adac-fb96-4cd8-9ae1-a767fdeec8c5)

The content of CSV except the filedir column:
![image](https://github.com/user-attachments/assets/342012f6-20fe-405b-b58a-6b5391123b4f)

The filedir column contain the paths for those files in this CSV file.

The error messages occurred with this structure of the BIDS directory and running the `qsmxt bids/ --- do_segmentations --auto_yes` command.

Thanks for referring me to the FastSurfer paper. I will take a look at it and see if I can find any related messages.

**Comment by astewartau** [comment]
Hi Huiyu,

Thanks for those details! I've been able to replicate your problem. It *should* be possible to run `qsmxt bids --do_segmentation --do_analysis --auto_yes`, but QSMxT in the current version still looks for phase images and does not continue processing without them - even though they are not needed. You could workaround this by adding phase images (if they are available), but I have also just fixed this in the main branch, and the next version, v7.2.0, will contain the fix. This version will be available in the next few hours, and I'll comment again when it is available, along with some instructions on how to access it. I've also added a test case to ensure these features remain working without phase files in the future. 

Thanks for helping to identify this bug!

**Comment by weblearn22** [comment]
Hi Ashley,

Thanks a lot for creating a new version to solve this issue! do not have phase images for those qsm images now, and thus I will test if the new version worked on my data.

**Comment by astewartau** [comment]
Hi @weblearn22 - I thought I would update you that the v7.2.0 version was released - I forgot to update you earlier. This one should fix the issue. :smile:

**Comment by weblearn22** [comment]
Hi @astewartau,

Thanks anyway for reminding me!

I tested it using the `qsmxt bids/ --do_segmentations --auto_yes` command again. But the problem did not solve on my end. Below are the related messages.

> [WARNING]: sub-*: Skipping QSM - No phase files found!
> [ERROR]: Workflow is empty! There is nothing to do.
>

**Comment by astewartau** [comment]
Hi @weblearn22 - are you sure that it is running the right version? You can confirm by checking the start of the log or running `qsmxt --version`. It should be v7.2.0. I just tried this as a test case without any phase images on Neurodesk:

```bash
(base) jovyan@neurodesktop-:~/example-notebooks/books/structural_imaging$ tree bids/
bids/
├── README
├── dataset_description.json
├── log_2024-09-04_03-53-54633971.txt
├── references.txt
├── sub-1
│   └── ses-20170705
│       ├── anat
│       │   ├── sub-1_ses-20170705_acq-mp2ragehighres0p5isoslab_run-01_T1w.json
│       │   ├── sub-1_ses-20170705_acq-mp2ragehighres0p5isoslab_run-01_T1w.nii
│       │   ├── sub-1_ses-20170705_acq-qsmp21mmisote20_run-01_part-mag_T2starw.json
│       │   └── sub-1_ses-20170705_acq-qsmp21mmisote20_run-01_part-mag_T2starw.nii
│       └── extra_data
│           └── dcm2niix_output.txt
└── sub-2
    └── ses-20170705
        ├── anat
        │   ├── sub-2_ses-20170705_acq-mp2ragehighres0p5isoslab_run-01_T1w.json
        │   ├── sub-2_ses-20170705_acq-mp2ragehighres0p5isoslab_run-01_T1w.nii
        │   ├── sub-2_ses-20170705_acq-qsmp21mmisote20_run-01_part-mag_T2starw.json
        │   └── sub-2_ses-20170705_acq-qsmp21mmisote20_run-01_part-mag_T2starw.nii
        └── extra_data
            └── dcm2niix_output.txt

8 directories, 14 files
(base) jovyan@neurodesktop-:~/example-notebooks/books/structural_imaging$ qsmxt bids/ --do_segmentation --auto_yes 
[INFO]: QSMxT v7.2.0
[INFO]: Python interpreter: /opt/miniconda-4.7.12.1/bin/python3.8
[INFO]: Command: qsmxt /home/jovyan/example-notebooks/books/structural_imaging/bids --do_segmentation --auto_yes
[INFO]: Available memory: 109.871 GB
[INFO]: Creating QSMxT workflow for sub-1.ses-20170705.acq-qsmp21mmisote20.run-01...
[INFO]: Creating QSMxT workflow for sub-2.ses-20170705.acq-qsmp21mmisote20.run-01...
[INFO]: Running using MultiProc plugin with n_procs=32
240904-03:55:05,424 nipype.workflow INFO:
         Workflow qsmxt-workflow settings: ['check', 'execution', 'logging', 'monitoring']
240904-03:55:05,451 nipype.workflow INFO:
         Running in parallel.
```

**Comment by weblearn22** [comment]
Hi @weblearn22,

I checked the version of QSMxT as you suggested. It is QSMxT v7.2.0. I have no idea why it did not work as you showed.

**Comment by astewartau** [comment]
Ahh, the issue is that the flag should be `--do_segmentation` and not `--do_segmentations`. I should add a warning for unrecognised parameters :P

**Comment by weblearn22** [comment]
You are right. `--do_segmentation` did work without any error after the csv file in the bids folder contained values in the MagnitudeFieldStrength and EchoTiem fields for the magnitude and t1 files. Is it possible to see the t1 images after they are co-registered with the magnitude images for each case? 

If I'd like to use the template to do the segmentation, which command should I use in detail? Is there anything I need to notice when preparing data in the bids folder for this case?

**Comment by astewartau** [comment]
Hi @weblearn22 - 

> Is it possible to see the t1 images after they are co-registered with the magnitude images for each case?

Yes. They are not included in the regular outputs, but you will find them in the QSMxT workflow directory (ie. `bids/derivatives/qsmxt-workflow`, within a subject folder and then a folder named something like `ants_register-t1-to-qsm`. 

> If I'd like to use the template to do the segmentation, which command should I use in detail?

You should be able to generate a cohort template using `qsmxt bids --do_template`. I just tested this, however, and the command does not work without also producing QSM images in the same command (i.e. `qsmxt bids --do_template --do_qsm`. I'm pushing an update v7.2.1 today which should fix this problem and allow users to generate a template using existing QSM images. 

QSMxT will give you QSM results and a template, all in the same cohort space. You should be able to segment the template in `bids/derivatives/qsmxt-xx-xx-xx/qsm_template/qsm_template.nii`, and the resulting segmentation should be usable with all of the QSM images in `bids/derivatives/qsmxt-xx-xx-xx/qsms_transformed/*.nii`. QSMxT does not yet automate a CSV analysis using a manually segmented template image, but this could be a feature added in a future version.

Hope that helps!

**Comment by weblearn22** [comment]
Hi @astewartau,

Thanks a lot for your response!

I can find the `ants_register-t1-to-qsm` folder. Which file contains t1 images, sub-*_ses-*_0GenericAffine.mat or result_ants_register-t1-to-qsm.pklz? How can I see the images from the file?

It would be convenient to use a version that can make a template just using `qsmxt bids --do_template` for my case. Hope to see that version in the future!

**Comment by astewartau** [comment]
Hi @weblearn22, I missed your last reply here. Hopefully, you figured it out! If not, here's a *very* late update:

a) In `ants_register-t1-to-qsm`, the `sub-_ses-_0GenericAffine.mat` file represents the transformation matrix that brings the T1 to the QSM space. The Transformed images are not in this directory, and the T1 images themselves are never transformed directly to the QSM space - only the transformation matrix is calculated. This matrix is applied to the segmentation to bring it into the QSM space. You'll find this in `ants_transform-segmentation-to-qsm`, or in the output directory as `qsm_segmentation`. You'll also find the segmentation in the T1 space as `t1w_segmentation`. 

b) QSMxT indeed uses ANTs. Specifically, antsRegistrationSyNQuick.sh. 

Thanks for the suggestion about having `--do_template` work on its own. I have since implemented this feature, and it works via e.g.:

```bash
qsmxt bids/ --do_template --use_existing_qsms
```

The existing QSM images need to exist in `bids/*/sub-<ID>/anat/*Chimap.nii`. There is not yet a way to run just the magnitude template-building part without any QSM images, but I could support this if there is still interest. 

Since this issue is now getting old, I'll close it for now, but am happy to re-open if you have any further issues, questions, or suggestions. Thanks!
